services:
  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  migrate:
    build:
      context: .
      target: migrator

  app:
    build:
      context: .
      target: dependencies
    command: npm run dev
    user: "0"
    ports:
      - "3000:3000"
    volumes:
      - .:/app:z
      - /app/node_modules
      - /app/.next
    environment:
      NODE_ENV: development
